version: '3.2'
services:
  taka_the_discord_bot_dependencies:
    image: taka_the_discord_bot_dependencies
    build: ./
  # taka_the_discord_bot_tetrio_html_server: # enable if you want to render tetrio image for /teto and /tetra
  #   build: ./taka_the_discord_bot_tetrio_html_server
  #   image: taka_the_discord_bot_tetrio_html_server    
  #   volumes:
  #     - ./taka_the_discord_bot_tetrio_html_server/assets:/taka_the_discord_bot_tetrio_html_server/assets
  #   depends_on:
  #     - taka_the_discord_bot_dependencies
  #   networks:
  #     - taka_the_discord_bot_tetrio_html_server_network
  taka_the_discord_bot_client:
    build: ./taka_the_discord_bot_client
    image: taka_the_discord_bot_client
    # volumes:
    #   - taka_the_discord_bot_client_chrome:/root/.local/share/headless-chrome/ # enable if you want to render tetrio image for /teto and /tetra
    #   - ./assets/taka_the_discord_bot_client:/taka_the_discord_bot_client/assets # enable if you want to render tetrio image for /teto and /tetra
    #   - ./conversations:/taka_the_discord_bot_client/conversations # enable if you want to use AI functionalities

    # links: # enable if you want to render tetrio image for /teto and /tetra
    #   - taka_the_discord_bot_tetrio_html_server 

    # external_links: # enable if you use a docker based database
    #   - taka_the_discord_bot_database
    depends_on:
      - taka_the_discord_bot_dependencies
      # - taka_the_discord_bot_tetrio_html_server # enable if you want to render tetrio image for /teto and /tetra
    networks:
      - taka_the_discord_bot_client_network
      # - taka_the_discord_bot_db_network # enable to use a docker based database
      # - taka_the_discord_bot_tetrio_html_server_network # enable if you want to render tetrio image for /teto and /tetra
networks: 
  taka_the_discord_bot_status_network: 
    name: taka_the_discord_bot_status_network
  taka_the_discord_bot_client_network:
    name: taka_the_discord_bot_client_network
  # taka_the_discord_bot_tetrio_html_server_network: # enable if you want to render tetrio image for /teto and /tetra
  #   name: taka_the_discord_bot_tetrio_html_server_network

  # taka_the_discord_bot_db_network: # enable if you use a docker based database
  #   name: taka_the_discord_bot_db_network
  #   external: true

# volumes: # enable to use the /teto and /tetra commands
#   taka_the_discord_bot_client_chrome:
#     name: taka_the_discord_bot_client_chrome